### ISSUE TITLE
WARNING: Assignment to undeclared global "heightStrength"

### ISSUE THREAD

**Issue by debagos** [random-geek/auroras#1]
First, I love this mod :)
Second, when I use it, it gives me a warning:
`WARNING[Server]: Assignment to undeclared global "heightStrength" inside a function at init.lua:227`

I know it's nothing "lethal" but I thought about letting you know about that little bug.
Minetest version: 5.3.0
MTG version: 5.3.0
Auroras version: 1.0.0

**Comment by random-geek** [comment]
Ah, I missed a `local`. It should be fixed now.

**Comment by debagos** [comment]
Yes, the warning is gone.
Issue is solved :)
Have a nice day Sir.
